mass : 1.1
aabb :
    length: 0.152
    width: 0.102
    height: 0.105
    center: [0.0, 0.0, 0.0]
mesh:
    xyz: [0.0, 0.0, 0.0]
    rpy: [0.0, 0.0, 0.0]
    filename: "package://bluespace_ai_xsens_mti_driver/urdf/MTI_1.stl"
    scale:
